[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"
default-run = "advent_of_code_2024"
publish = false

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
thiserror = "2.0.3"
ureq = "2.11.0"

